[package]
name = "ros"
version = "0.1.0"
authors = ["Gabriel Berto <gabrielberto@protonmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
